name: "build"
on: push
jobs:
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'
    - run: ./gradlew build --no-daemon